'use client'

import { useState } from 'react'
import { CalendarEvent } from '@/lib/types'

// Returns the Monday and Sunday of the current week as YYYY-MM-DD strings
function getCurrentWeekBounds(): { start: string; end: string; label: string } {
  const today = new Date()
  const dayOfWeek = today.getDay() // 0 = Sun
  const monday = new Date(today)
  monday.setDate(today.getDate() - ((dayOfWeek + 6) % 7))
  const sunday = new Date(monday)
  sunday.setDate(monday.getDate() + 6)

  const fmt = (d: Date) => d.toISOString().split('T')[0]
  const labelFmt = (d: Date) =>
    d.toLocaleDateString('en-GB', { day: 'numeric', month: 'long', year: 'numeric' })

  return { start: fmt(monday), end: fmt(sunday), label: labelFmt(monday) }
}

// Format HH:MM:SS → HH:MM
function fmtTime(t: string | null | undefined) {
  if (!t) return null
  return t.slice(0, 5)
}

// Format YYYY-MM-DD → "Monday 14 April"
function fmtDate(d: string) {
  return new Date(d + 'T00:00:00').toLocaleDateString('en-GB', {
    weekday: 'long',
    day: 'numeric',
    month: 'long',
  })
}

// Build a plain-text digest from a list of events grouped by date
function buildDigestText(events: CalendarEvent[], weekLabel: string): string {
  if (events.length === 0) {
    return `Weekly Training & Events Digest — w/c ${weekLabel}\n\nNo events scheduled for this week.`
  }

  // Group by date
  const byDate: Record<string, CalendarEvent[]> = {}
  for (const e of events) {
    if (!byDate[e.event_date]) byDate[e.event_date] = []
    byDate[e.event_date].push(e)
  }

  const lines: string[] = [
    `Weekly Training & Events Digest — w/c ${weekLabel}`,
    `${'─'.repeat(50)}`,
    '',
  ]

  for (const date of Object.keys(byDate).sort()) {
    lines.push(fmtDate(date))
    lines.push('─'.repeat(30))
    for (const e of byDate[date]) {
      const start = fmtTime(e.start_time)
      const end = fmtTime(e.end_time)
      const timeStr = start ? (end ? `${start}–${end}` : start) : 'Time TBC'
      const format = e.delivery_mode ?? (e.location ? 'In Person' : 'TBC')
      const location = e.location ? ` — ${e.location}` : ''

      lines.push(`• ${e.title}`)
      lines.push(`  Time: ${timeStr}`)
      if (e.target_audience) lines.push(`  Audience: ${e.target_audience}`)
      lines.push(`  Format: ${format}${location}`)
      if (e.description) {
        // Trim long descriptions to ~120 chars
        const desc = e.description.length > 120
          ? e.description.slice(0, 117) + '…'
          : e.description
        lines.push(`  Summary: ${desc}`)
      }
      if (e.booking_url) lines.push(`  Book: ${e.booking_url}`)
      lines.push('')
    }
  }

  lines.push('─'.repeat(50))
  lines.push('Generated by CWTH Events Calendar')

  return lines.join('\n')
}

type CopyState = 'idle' | 'loading' | 'copied' | 'empty' | 'error'

export default function DigestPanel() {
  const [copyState, setCopyState] = useState<CopyState>('idle')
  const [eventCount, setEventCount] = useState<number | null>(null)
  const [digestText, setDigestText] = useState<string | null>(null)

  async function handleGenerateAndCopy() {
    setCopyState('loading')
    setDigestText(null)

    try {
      const { start, end, label } = getCurrentWeekBounds()

      // Fetch only this week's published events
      const params = new URLSearchParams()
      // We'll fetch all and filter client-side since the API doesn't have date-range params
      const res = await fetch('/api/events', { cache: 'no-store' })
      if (!res.ok) throw new Error('Failed to fetch events')

      const data = await res.json()
      const allEvents: CalendarEvent[] = data.events ?? []

      // Filter to current week only
      const weekEvents = allEvents.filter(
        e => e.event_date >= start && e.event_date <= end
      )

      setEventCount(weekEvents.length)

      if (weekEvents.length === 0) {
        const text = buildDigestText([], label)
        setDigestText(text)
        await navigator.clipboard.writeText(text)
        setCopyState('empty')
        return
      }

      const text = buildDigestText(weekEvents, label)
      setDigestText(text)
      await navigator.clipboard.writeText(text)
      setCopyState('copied')

      // Reset after 4 seconds
      setTimeout(() => setCopyState('idle'), 4000)
    } catch {
      setCopyState('error')
      setTimeout(() => setCopyState('idle'), 3000)
    }
  }

  return (
    <div className="space-y-6 max-w-3xl">

      {/* How it works */}
      <div className="bg-cwth-light-blue rounded-lg p-5 border border-blue-200">
        <h2 className="text-base font-bold text-cwth-dark mb-1">How it works</h2>
        <ol className="text-sm text-cwth-dark space-y-1 list-decimal list-inside">
          <li>Click <strong>Generate Weekly Digest</strong> to compile this week&apos;s events.</li>
          <li>The formatted digest is copied to your clipboard automatically.</li>
          <li>Paste directly into Outlook or any email client and send manually.</li>
        </ol>
        <p className="text-xs text-cwth-mid-grey mt-2">
          This avoids NHS mailing list restrictions — the digest is generated entirely in your browser.
        </p>
      </div>

      {/* Generate & Copy button */}
      <div className="flex flex-col sm:flex-row sm:items-center gap-3">
        <button
          onClick={handleGenerateAndCopy}
          disabled={copyState === 'loading'}
          className="inline-flex items-center gap-2 px-5 py-2.5 bg-cwth-teal text-white font-semibold rounded-md hover:bg-teal-600 transition-colors disabled:opacity-60 disabled:cursor-not-allowed"
        >
          {copyState === 'loading' ? (
            <>
              <svg className="animate-spin h-4 w-4" fill="none" viewBox="0 0 24 24">
                <circle className="opacity-25" cx="12" cy="12" r="10" stroke="currentColor" strokeWidth="4" />
                <path className="opacity-75" fill="currentColor" d="M4 12a8 8 0 018-8V0C5.373 0 0 5.373 0 12h4z" />
              </svg>
              Generating…
            </>
          ) : (
            <>
              <svg className="h-4 w-4" fill="none" viewBox="0 0 24 24" stroke="currentColor" strokeWidth={2}>
                <path strokeLinecap="round" strokeLinejoin="round" d="M8 16H6a2 2 0 01-2-2V6a2 2 0 012-2h8a2 2 0 012 2v2m-6 12h8a2 2 0 002-2v-8a2 2 0 00-2-2h-8a2 2 0 00-2 2v8a2 2 0 002 2z" />
              </svg>
              Generate Weekly Digest
            </>
          )}
        </button>

        {/* Status feedback */}
        {copyState === 'copied' && (
          <span className="flex items-center gap-1.5 text-sm font-semibold text-green-700">
            <svg className="h-4 w-4" fill="none" viewBox="0 0 24 24" stroke="currentColor" strokeWidth={2.5}>
              <path strokeLinecap="round" strokeLinejoin="round" d="M5 13l4 4L19 7" />
            </svg>
            Weekly digest copied to clipboard — paste into Outlook to send.
          </span>
        )}
        {copyState === 'empty' && (
          <span className="text-sm text-cwth-mid-grey">
            No events this week — empty digest copied to clipboard.
          </span>
        )}
        {copyState === 'error' && (
          <span className="text-sm text-red-600">
            Could not copy to clipboard. Check your browser permissions.
          </span>
        )}
        {eventCount !== null && copyState === 'idle' && (
          <span className="text-sm text-cwth-mid-grey">
            Last run: {eventCount} event{eventCount !== 1 ? 's' : ''} found this week.
          </span>
        )}
      </div>

      {/* Digest preview */}
      {digestText && (
        <div className="border border-cwth-border rounded-lg overflow-hidden">
          <div className="bg-gray-50 px-4 py-2 border-b border-cwth-border flex items-center justify-between">
            <span className="text-xs font-semibold text-cwth-mid-grey uppercase tracking-wide">
              Digest Preview
            </span>
            <span className="text-xs text-cwth-mid-grey">
              Plain text — paste directly into Outlook
            </span>
          </div>
          <pre className="p-4 text-xs text-cwth-dark font-mono whitespace-pre-wrap leading-relaxed overflow-auto max-h-96 bg-white">
            {digestText}
          </pre>
        </div>
      )}
    </div>
  )
}
